### PR TITLE
add local storage support

### PR DESCRIPTION
**Pull request by glazec**
I have tested under adding contract ABI.
CleanShot 2021-12-30 at 16 38 30@2x

### CODE REVIEW

**Comment by glazec** [comment]
If you follow the following steps, the program will stuck. I am not sure why it stuck:
1. add contract
2. refresh the page
3. click contract
4. click contract's function

**Comment by adrianmcli** [comment]
Thanks @glazec

**Comment by stwiname** [comment]
> If you follow the following steps, the program will stuck. I am not sure why it stuck:
> 
>     1. add contract
> 
>     2. refresh the page
> 
>     3. click contract
> 
>     4. click contract's function

I have the same problem now.

My guess would be that here's a react hook with a dependency of itself

**Comment by IKIGUYZ** [comment]
> 

https://github.com/adrianmcli/eth95/pull/45

**Comment by IKIGUYZ** [comment]
> > If you follow the following steps, the program will stuck. I am not sure why it stuck:
> > ```
> > 1. add contract
> > 
> > 2. refresh the page
> > 
> > 3. click contract
> > 
> > 4. click contract's function
> > ```
> 
> I have the same problem now.
> 
> My guess would be that here's a react hook with a dependency of itself

I fix your issue and create new pull request, @adrianmcli please review and merge this pull request. https://github.com/adrianmcli/eth95/pull/45

**Pull request merged**
