### PR TITLE
Update react and dependencies

### PR DESCRIPTION
**Pull request by samuelmarshall**
Tried not to make any major changes. Just updated dependencies and then fixed any breaking changes resulting from the updates. Looking to fix some of the issues people have requested, but wanted to update first. All tests are passing and I couldn't find any new bugs from my own manual testing. Happy to make any further edits or changes that you see fit.

### CODE REVIEW

**Comment by adrianmcli** [comment]
Thanks for doing this, but it looks like the build is failing?

**Comment by samuelmarshall** [comment]
Does Vercel give you any insight into why the build failed? I can't see any details. If the tests are failing, it could be that truffle and ganache are no longer dependencies in the main package.json, my local environment has global versions of both so I forgot about them, other than that I'm not sure. Locally, all tests pass, and I can run project with "ts-node src/index.ts" and "node dist/index.js".

**Comment by adrianmcli** [comment]
Let me dump the log here:

```
[12:31:52.518] Cloning github.com/adrianmcli/eth95 (Branch: update, Commit: dca7260)
[12:31:52.953] Cloning completed: 434.979ms
[12:31:53.809] No Build Cache available
[12:31:53.845] Running "vercel build"
[12:31:54.366] Vercel CLI 28.2.5
[12:31:54.589] Error: Node.js version 12.x has reached End-of-Life. Deployments created on or after 2022-10-01 will fail to build. Please set Node.js Version to 16.x in your Project Settings to use Node.js 16.
[12:31:54.591] Installing dependencies...
[12:31:54.947] yarn install v1.22.17
[12:31:55.023] [1/4] Resolving packages...
[12:31:55.509] [2/4] Fetching packages...
[12:32:09.311] error husky@8.0.1: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.11"
[12:32:09.319] error Found incompatible module.
[12:32:09.320] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[12:32:09.345] Error: Command "yarn install" exited with 1
```

**Comment by adrianmcli** [comment]
Looks like an issue w/ the node version and incompatibility w/ Husky. Can you see if updating `package.json` with an `engines` entry along w/ a compatible version of husky can make this work?

**Comment by adrianmcli** [comment]
@samuelmarshall really great work Sam, I appreciate it a lot. This sets the stage for modernizing the tool. Do you have any thoughts about dropping the support for local projects (i.e. Truffle/Hardhat) and having the project to be focused on a standalone frontend UI instead?

**Comment by samuelmarshall** [comment]
no problem! I like a standalone UI. The only thing we would be losing would be the artifact path, correct? I don't think that's a big issue, especially if I can fix some of the state issues, and clean up the process of adding contracts by abi/address.

**Pull request merged**
